### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by sharmaansh21**
- [x] `curl -i http://testserver.lan` will return 502 response
- [x]  Nginx as a loadbalancer
- [x]  Environment configuration
- [x] Graceful shutdown 
- [x] Docker images Optimisation
- [x] Nginx TLS
- [ ] Application TLS

### CODE REVIEW

**Comment by sharmaansh21** [comment]
In the second issue, I used
```
ip=$(hostname -i)
/usr/local/bin/testserver -address $ip
```
and in the fourth, I replaced that with address 0.0.0.0. I am not sure how to pass IP address with entrypoint or cmd

**Comment by sharmaansh21** [comment]
@spinx Ready for review, I am unable to figure it how to fix 6.2. Getting
```
testserver_1    | 2019/08/12 13:55:15 http: TLS handshake error from 172.80.1.3:55984: tls: first record does not look like a TLS handshake
```
While trying to ssl certs for go app.

**Comment by spinx** [comment]
@sharmaanshul21 just closing this so it's not public. Will reach over email.

**Comment by sharmaansh21** [comment]
@spinx thanks

**Pull request closed without merging**
